const PREFIX = "student";

export const GET_STUDENT_PENDING = `${PREFIX}/GET_PRODUCTS_PENDING`;
export const GET_STUDENT_FULLFILED = `${PREFIX}/GET_PRODUCTS_FULLFILED`;
export const GET_STUDENT_REJECTED = `${PREFIX}/GET_PRODUCTS_REJECTED`;

export const CHANGE_SEARCH_VALUE = `${PREFIX}/CHANGE_SEARCH_VALUE`;
